### ISSUE TITLE
Enforce that if request/correlation id provided, it must be a UUID otherwise generate new

### ISSUE THREAD

**Issue by derekbekoe** [tomwojcik/starlette-context#10]
**Issue**
Currently, any value is accepted.

**Expectation**
Only UUIDs should be accepted.

The could be implemented with a new kwarg on the Plugins so this isn't a breaking change for any users who currently accept request values that are not UUIDs.

**Relevant source code**
https://github.com/tomwojcik/starlette-context/blob/79aa8ffe5b50db2263e2073fc5d252bf442f150c/starlette_context/plugins/correlation_id.py#L14-L22

Happy to submit a PR if needed.

**Comment by tomwojcik** [comment]
Makes sense.

Feel free to open a PR or I'll do that myself over the weekend.
