### ISSUE TITLE
Python 3.6 installs 0.1.3 version

### ISSUE THREAD

**Issue by tuukkamustonen** [tomwojcik/starlette-context#14]
Seems like new releases are no longer publish for python 3.6 (even with `contextvars` library). This should probably be noted in the README?

On python 3.6.6 (and 0.1.3) I faced error:

```
...
  File "/home/musttu/.pyenv/versions/3.6.6/envs/famp/lib/python3.6/site-packages/starlette_context/middlewares/basic_context_middleware.py", line 1, in <module>
    from _contextvars import Token
ModuleNotFoundError: No module named '_contextvars'
```

**Comment by tomwojcik** [comment]
Thank you for reporting this. I will just remove the line about python3.6 from the readme.
