### ISSUE TITLE
PluginUUIDBase's force_new_uuid option seems broken

### ISSUE THREAD

**Issue by wapiflapi** [tomwojcik/starlette-context#15]
When using `PluginUUIDBase`'s `force_new_uuid` option and setting it to `True` I'm always getting the same `uuid`. Which is the **opposite** of what I expect.

It looks like when `self.value is None` a new `uuid` is generated, and this works fine when for the first request. But subsequent request seem to be using the same id.  

I suspect the code that needs to be fixed is missing a `self.value = None` before trying anything else here:
https://github.com/tomwojcik/starlette-context/blob/2f80262bbf4c00fb501c22ac04a5c1c408187fe6/starlette_context/plugins/plugin_uuid.py#L34

**Comment by wapiflapi** [comment]
Thinking about this, why is `self.value` being used anyway? I don't understand why this is being stored on the plugin instance. It seems like a normal variable would be enough and match the intend better, and it would have avoided this bug.

**Comment by tomwojcik** [comment]
Hey, thanks for opening this ticket. Indeed that's a bug. I'll fix this within a few days.

**Comment by tomwojcik** [comment]
0.2.3 is published. Please try again and let me know if it's all good now.

**Comment by wapiflapi** [comment]
Looks good from here! 

Thank you for the quick fix.

FTR my workaround was:

```python

# Fix https://github.com/tomwojcik/starlette-context/issues/15

__original_extract_value_from_header_by_key = (
    PluginUUIDBase.extract_value_from_header_by_key)


async def __patched_extract_value_from_header_by_key(self, request):
    self.value = None
    return await __original_extract_value_from_header_by_key(self, request)


PluginUUIDBase.extract_value_from_header_by_key = (
    __patched_extract_value_from_header_by_key
)
```

**Removing** this from my code, and using `0.2.3` all my tests still pass.
:fireworks:  For me it looks good!

**Comment by tomwojcik** [comment]
Awesome! Thanks for checking that out.
