### ISSUE TITLE
rewrite middleware to pure ASGI

### ISSUE THREAD

**Issue by dmig-alarstudios** [tomwojcik/starlette-context#18]
Since there are issues in Starlette caused by `BaseHTTPMiddleware` class, this package becomes a source of these issues in any project using it:
- https://github.com/encode/starlette/issues/919
- https://github.com/encode/starlette/issues/1012

The simple solution would be to rewrite the middleware to pure ASGI.

**Comment by tomwojcik** [comment]
Hmm, good point. I never heard about this issue before and I'm not affected by this. I will definitely rewrite this to pure ASGI at some point as it seems like there are no downsides of the solution you suggest but I will give it some time until the creators of Starlette decide what to do next. From what I read in the tickets you linked it seems like the middleware that's supposed to be inherited is just broken.

**Comment by dmig-alarstudios** [comment]
Not in some cases. It's broken by design.
Problems are: `ReadTimeout`s, if using `BaseHTTPMiddleware`-based middleware along with `BackgroundTask`s and huge memory usage because `BaseHTTPMiddleware` spools everything in memory.

**Comment by dmig-alarstudios** [comment]
Here is a nice and simple example of ASGI middleware: https://github.com/encode/starlette/blob/master/starlette/middleware/sessions.py

**Comment by tomwojcik** [comment]
Yeah, I see. I will rewrite it over the weekend. Thanks for letting me know.

**Comment by tomwojcik** [comment]
@dmig-alarstudios 0.3.0 published with what should be a functioning "raw" middleware. Let me know if it doesn't work as expected.
