### ISSUE TITLE
Add request-id to logs without using LoggerAdapter

### ISSUE THREAD

**Issue by dev-99** [tomwojcik/starlette-context#19]
Thank you for this middleware!

I want to use it for adding request IDs in the logs of third-party libraries that I do not have control over. Since most libraries might use a logger instead of LoggerAdapter, I am wondering if there is a way to log request IDs without the use LoggerAdapter(like in the example given in this repo).

**Comment by tomwojcik** [comment]
I'm glad you like it!

For sure you can do it but I don't think there's anything I need to add in order to make it work. But lets crack it together. Could you please give me an example? What 3rd party lib?

**Comment by yinkh** [comment]
log_request_id.py

import logging
from starlette_context import context


def get_request_id():
    return context.data['X-Request-ID']


```
class RequestIDLogFilter(logging.Filter):
    """
    Log filter to inject the current request id of the request under `log_record.request_id`
    """

    def filter(self, log_record):
        log_record.request_id = get_request_id()
        return log_record
```

```
class RequestLogHandler(LogHandler):
    log_format = REQUEST_ID_LOG_FORMAT

    def __setFileHandler__(self, level=None):
        super(RequestLogHandler, self).__setFileHandler__(level=level)
        self.addFilter(RequestIDLogFilter())

    def __setStreamHandler__(self, level=None):
        super(RequestLogHandler, self).__setStreamHandler__(level=level)
        self.addFilter(RequestIDLogFilter())
```
`REQUEST_ID_LOG_FORMAT = '%(asctime)s [pid:%(process)d] %(filename)s(line:%(lineno)d) %(levelname)s [%(request_id)s] %(message)s'`
log = RequestLogHandler('client')

logging inside api :

`log.info('demo')` get 
`2020-09-30 13:57:43,563 [pid:12340] views.py(line:362) INFO [c493912529a14849ba6475a56af6407e] demo`
what do you think?

**Comment by tomwojcik** [comment]
I added a working example with:
- async logger
- setup from dict
- without adapter

https://starlette-context.readthedocs.io/en/latest/example.html
