### ISSUE TITLE
JWT token?

### ISSUE THREAD

**Issue by Feijo** [tomwojcik/starlette-context#28]
Is there a way to access the authorization header to capture the JWT token?

**Comment by Feijo** [comment]
Ended up creating my own plugin:

```
from starlette_context.plugins.base import Plugin

class AuthorizationPlugin(Plugin):
    key = 'Authorization'
```

Perhaps this one could be added to the built-in plugins?

**Comment by tomwojcik** [comment]
Sure. PR is welcome.

**Comment by tomwojcik** [comment]
I was thinking about that and I think it's a bad practice to store it anywhere else than in the request object. After all, you should only use it to validate the request. 

I'm closing this ticket. If your case needs it - just do as @Feijo has shown.

Thanks.
