### ISSUE TITLE
Test fails due to an uninitialized context

### ISSUE THREAD

**Issue by brunoripa** [tomwojcik/starlette-context#35]
I have a FastAPI app, that is the same used in the `py.test` unit tests. Also, `RawContextMiddleware` is the only middleware I have, coming from `startlette_context`, of course. 

Responsibility of the middleware is to read the value of a custom http header, and put something in the context object. It works perfectly if I test the app, but when I run tests (which were already in place and successfully executed _before_ I added `startlette_middleware`) a couple break, with the following:

```
You didn't use ContextMiddleware or you're trying to access context object outside of the request-response cycle
```

Maybe starlette `TestClient` requires some specific setup to deal with middlewares ?

**Comment by tomwojcik** [comment]
Weird. Could you provide a reproducible example? The entire test case with fixtures etc.

**Comment by brunoripa** [comment]
I will try to create one in the next 2-3 days; that code is from one of my clients, so I can't copy&paste

**Comment by brunoripa** [comment]
I was creating a minimal project with `starlette_context` and custom plugin to replicate my problem, but I have tests working properly. So I think that somehow the problem is in our project. So, I am closing this issue, and I'll re-open if needed. Thanks for your time.
