### ISSUE TITLE
Question: Can I add request-id into uvicorn.access log?

### ISSUE THREAD

**Issue by tienhm0202** [tomwojcik/starlette-context#40]
My log now is:
```
[2021-04-25 08:48:58 +0000] [13] [INFO] RID: ad303ddacea942b89c6f08e33b5f09be | CID: d68deb856ea84d4e8e7bc7c08bc511bd | s.m.users.business.controllers | An user is trying to log in our system

[2021-04-25 08:48:58 +0000] [13] [INFO] uvicorn.access | 172.21.0.1:64268 - "POST /v1/users/login HTTP/1.1" 200
```

I tried to add filter to log request-id and correlation-id to uvicorn.access but it raised `starlette_context.errors.ContextDoesNotExistError`.

Is there a way to add context data to uvicorn.access log?

**Comment by tienhm0202** [comment]
Look like context is closed right in RawContextMiddleware - I will try another

**Comment by tomwojcik** [comment]
Yes, it's not possible to use `context` in uvicorn.

https://github.com/encode/uvicorn/pull/859

You can see it's still changing. A few months ago the behavior you desire was there by default and now it's not even possible to add headers to logs, if I read it correctly. If I were you I'd not rely on uvicorn logs AT ALL but rather add a proxy server where you will have total control over it and much more. Then, send logs to a centralized server.

So if you're willing to overengineer it:
- add [traeffic](https://doc.traefik.io/traefik/observability/access-logs/#limiting-the-fieldsincluding-headers) / [caddy](https://caddyserver.com/docs/logging#emission)
- add ELK or something else where you can browse logs

Or just use `0.13.0` where I believe response scope was logged.
