### ISSUE TITLE
Extract data from the request body

### ISSUE THREAD

**Issue by andrei-shabanski** [tomwojcik/starlette-context#5]
Are there future plans to support getting the context data from the request body?

`Plugin.process_request` isn't able to call async methods, so no way to use the request body in plugins now. 

This feature would make benefits to log exceptions for instance.

**Comment by tomwojcik** [comment]
To be honest I forgot it's required for body and I don't need it for my use case but it makes sense to have it. Answering your question yes, I will implement it soon when I find some spare time. Thanks for reminding me about that.
