### ISSUE TITLE
Improving the __repr__ method of _Context

### ISSUE THREAD

**Issue by zachary822** [tomwojcik/starlette-context#65]
`UserDict.__repr__` attempting to print the contents of `_Context.data` outside of a starlette app raises `starlette_context.errors.ContextDoesNotExistError`. Can we make the `__repr__` return something that indicates that rather than raising exception?

Current problem:

```
# some route.py
"""
Module docstring
"""
from starlette_context import context
...

# in python console
import route
help(route)  # raises exception
```

**Comment by tomwojcik** [comment]
@hhamana fixed this in #66. I'll release the fix within a week, I think. Thanks for opening the issue.
