### ISSUE TITLE
Exceptions should inherit from Exception, not BaseException

### ISSUE THREAD

**Issue by soundstripe** [tomwojcik/starlette-context#90]
It seems to me like `StarletteContextError` in `errors.py` should subclass `Exception` instead of `BaseException`.

Exceptions that inherit from BaseException are not caught by the normal try/catch idiom of:

```
try:
    block_of_code()
exception Exception as e:
    handle(e)
```

BaseException is meant for exception types that _shouldn't_ be caught by normal handlers (SystemInterrupt, etc).

If this was an intentional decision on your part, that's fine, but I didn't see any issues or discussion about it. I'd be happy to submit a PR for this if you like.

I love this package and I use it in a few of my FastAPI projects!

**Comment by tomwojcik** [comment]
Released in [v0.3.6](https://github.com/tomwojcik/starlette-context/releases/tag/v0.3.6) .

Thank you again! I'm very happy `starlette-context` gained another contributor.
